version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - MONGODB_URL=${MONGODB_ATLAS_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - UPLOAD_DIR=/shared_volume
    volumes:
      - shared_volume:/shared_volume
    restart: unless-stopped
    depends_on:
      - rabbitmq

  consumer:
    build: .
    command: python consumer.py
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - MONGODB_URL=${MONGODB_ATLAS_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - shared_volume:/shared_volume
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started


  redis:
    image: redis



  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

   

volumes:
  shared_volume:
  rabbitmq_data: