FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    poppler-utils \
    tesseract-ocr \
    libtesseract-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy entire app directory
COPY ./app /app

# Set Python path
ENV PYTHONPATH=/app

CMD ["python", "-m", "consumer"]  # Direct module execution